spring:
  application:
    name: securityStudy
  config:
    import: optional:file:.env[properties]

  # MySQL DB connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA ddl, Naming and log
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}